config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "schedule#index"

  resources :schedule do 
    get :detail, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
    belongs_to :user

    validates :initial_time, :final_time, :user_id, presence: true
    validate :final_greater_than_initial
    validate :overlap?

    scope :week, -> (week_begin, week_end) {where("initial_time >= ? and final_time < ?", week_begin, week_end)}
    
    def overlap?
        r = Schedule.where("(? >= initial_time and ? < final_time) or (? >= initial_time and ? < final_time)", initial_time, initial_time, final_time, final_time)
                .where.not(id: self.id).size > 0
        if r
            errors.add(:initial_time, "Horário #{self.initial_time} ou #{self.final_time} sobrepõe com horário já existente: ")
        end
        r
    end

    #está dentro do prazo de edição que é 'dentro da semana'?
    def editable?
        Date.today.get_working_week_period[1] <= self.initial_time.to_date.get_working_week_period[1]
    end

    private
    def final_greater_than_initial
        if self.final_time <= self.initial_time
           errors.add(:final_time, "Final precisa ser maior que o inicial.")
        end
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :schedules

  validates :name, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!

    protected

     def configure_permitted_parameters
          devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}
          devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
     end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        redirect_to schedule_path()
    end
end

app/controllers/schedule_controller.rb
class ScheduleController < ApplicationController
    def index
        @day = params["date"] ? Date.parse(params["date"]) : Date.today
        @week_begin, @week_end = @day.get_working_week_period
        @schedule = {}
        Schedule.select(:id, :user_id, :initial_time).includes(:user).week(@week_begin, @week_end).each do |s|
            @schedule[s.initial_time.wday] ||= {}
            @schedule[s.initial_time.wday][s.initial_time.hour] = s
        end
    end

    def detail
        schedule = Schedule.includes(:user).find(params["id"])
        render json: {
            schedule: {
                id: schedule.id,
                initial_time: schedule.initial_time.strftime("%Y-%m-%dT%H:%M"),
                final_time: schedule.final_time.strftime("%Y-%m-%dT%H:%M"),
                description: schedule.description
            },
            username: schedule.user.name
        }
    end

    def create
        schedule = Schedule.new
        schedule.initial_time   = params["initial_time"]
        schedule.final_time     = params["final_time"]
        schedule.description    = params["description"]
        schedule.user_id        = current_user.id
        
        if schedule.editable?
            if schedule.save
                render json: {}, status: 200
            else
                render json: {msg: schedule.errors.first.type}, status: 400
            end
        else
            render json: {msg: "Fora do prazo de edição."}, status: 400
        end
    end

    def update        
        schedule = Schedule.where(id: params["id"], user_id: current_user.id)[0]
        if schedule
            schedule.initial_time   = params["initial_time"]
            schedule.final_time     = params["final_time"]
            schedule.description    = params["description"]
            if schedule.save
                render json: {}, status: 200
                return
            end
        end
        msg = schedule.errors.first.type rescue "Operação não permitida"
        render json: {msg: msg}, status: 400
    end

    def destroy
        schedule = Schedule.where(id: params["id"], user_id: current_user.id)[0]
        if schedule
            schedule.destroy
            render json: {}, status: 200
        else
            #não pode deletar agenda do coleguinha
            render json: {msg: "Operação não permitida"}, status: 400
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def parse_initial_time week_begin, wday, hour
        (week_begin + wday.day).strftime("%Y-%m-%dT#{hour.to_s.rjust(2, "0")}:00")
    end

    #sugere o intervalo de 1h sugerido no desenvolvimento
    def parse_final_time week_begin, wday, hour
        parse_initial_time(week_begin, wday, hour + 1)
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testedev</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
      <div class="navbar-text float-right">
        <% if user_signed_in? %>
          User: <strong><%= current_user.name %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </div>

      <% if notice %>
        <p class="notice"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert"><%= alert %></p>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/schedule/_detail.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">x</button>
</div>
<div class="modal-body">
  <input hidden name="id">
  <div class="field">
    Reserva de <strong name="username">?</strong>
  </div>
  
  <div class="field">
    <label>Inicio</label><br>
    <input name="initial_time" type="datetime-local" value="">
  </div>

  <div class="field">
    <label>Fim</label><br>
    <input name="final_time" type="datetime-local" value="">
  </div>
  
  <div class="field">
    <label>Descrição</label><br>
    <textarea name="description">
    </textarea>
  </div>
  <input type="submit" class="btn btn-primary" onclick="detail_submit()">
</div>
<div class="modal-footer">
</div>

app/views/schedule/index.erb
<div class="container">
    <h2>
        <%= link_to "< Semana Anterior", root_path(date: @day - 7.days)%>
        Semana de <%=@week_begin.strftime("%d/%m/%Y") %> a <%=(@week_end - 1.day).strftime("%d/%m/%Y") %>
        <%= link_to "Próxima Semana >", root_path(date: @day + 7.days)%>
    </h2>
    <table>
        <tr>
            <th>Horário</th>
            <th>Segunda</th>
            <th>Terça</th>
            <th>Quarta</th>
            <th>Quinta</th>
            <th>Sexta</th>
        </tr>
        <% (6..23).each do |hour| %>
        <tr>
            <td><%=hour.to_s.rjust(2, "0")%>:00</td>
            <% (1..5).each do |day| %>
                <td id="td_<%=day%>_<%=hour%>">
                <% if @schedule[day] && @schedule[day][hour] %>
                    <div class="row">
                        <div class="col" onclick="detail_schedule('<%=detail_schedule_path(@schedule[day][hour].id)%>')">
                            Reservado para <strong><%=@schedule[day][hour].user.name%></strong>
                        </div>
                        <div class="delete-x col" title="Cancelar reserva" onclick="remove_schedule('<%=@schedule[day][hour].id%>');">
                            X
                        </div>
                    </div>
                <% else %>
                    <div onclick="detail_fulfill('', '<%=parse_initial_time(@week_begin -1.day, day, hour)%>', '<%=parse_final_time(@week_begin -1.day, day, hour)%>', '', '<%=current_user.name%>')">Disponível</div>
                <% end %>
                </td>
            <% end %>
        </tr>
        <% end %>
    </table>
</div>
<div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content"><%=render "schedule/detail"%></div>
    </div>
</div>